export const INIT = [
  {
    event_id: '1',
    user_account_id: '001',
    category: '연차',
    start_date: '2023/03/01',
    end_date: '2023/03/03',
    created_by: '등록한 사람',
    created_at: '등록날짜',
    modified_by: '수정한 사람',
    modified_at: '수정날짜',
    name: '가',
    email: '001@gamil.com',
  },
  {
    event_id: '2',
    user_account_id: '001',
    category: '당직',
    start_date: '2023/03/23',
    end_date: '2023/03/24',
    created_by: '등록한 사람',
    created_at: '등록날짜',
    modified_by: '수정한 사람',
    modified_at: '수정날짜',
    name: '가',
    email: '001@gamil.com',
  },
  {
    event_id: '3',
    user_account_id: '002',
    category: '당직',
    start_date: '2023/03/11',
    end_date: '2023/03/12',
    created_by: '등록한 사람',
    created_at: '등록날짜',
    modified_by: '수정한 사람',
    modified_at: '수정날짜',
    name: '나',
    email: '002@gamil.com',
  },
  {
    event_id: '4',
    user_account_id: '003',
    category: '연차',
    start_date: '2023/03/22',
    end_date: '2023/03/25',
    created_by: '등록한 사람',
    created_at: '등록날짜',
    modified_by: '수정한 사람',
    modified_at: '수정날짜',
    name: '다',
    email: '003@gamil.com',
  },
  {
    event_id: '5',
    user_account_id: '002',
    category: '연차',
    start_date: '2023/03/29',
    end_date: '2023/04/01',
    created_by: '등록한 사람',
    created_at: '등록날짜',
    modified_by: '수정한 사람',
    modified_at: '수정날짜',
    name: '나',
    email: '002@gamil.com',
  },
  {
    event_id: '6',
    user_account_id: '004',
    category: '당직',
    start_date: '2023/03/22',
    end_date: '2023/03/23',
    created_by: '등록한 사람',
    created_at: '등록날짜',
    modified_by: '수정한 사람',
    modified_at: '수정날짜',
    name: '라',
    email: '004@gamil.com',
  },
];

export const USER_ID = '001';
